Repository thrishank/solanascore, pull requests merged in 2025-02, with the labels that each got.

#11 demo
  README.md
Labels: small

#10 Update README.md
  README.md
Labels: bug, enhancement, easy

#12 Update README.md
  README.md
Labels: easy

#13 Update README.md
  README.md
Labels: easy
